name: Vigilnz Scan
on: 
  push: # runs on every push 
  workflow_dispatch: # lets you run manually from the Actions tab

jobs:
  Vigilnz_Scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Vigilnz Scan
        uses: Susenthiran28/custom-github-action@master
        with:
          vigilnzApiKey: "vigil_69254d8ffff5ddd9ac8e076e_TAYYVCUO6DSS53WF"
          scanTypes: "sca,sbom,sast"
