name: Vigilnz Scan
on: [push]

jobs:
  Vigilnz Scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Vigilnz Scan
        uses: Susenthiran28/custom-github-action@master
        with:
          vigilnzApiKey: "vigil_69254d8ffff5ddd9ac8e076e_TAYYVCUO6DSS53WF"
          scanTypes: "sca,sbom,sast"
